version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
   commands:
      - echo Bulid the Json code
      - echo Build started on `date`
      - npm run test
      - package.json
      - basic_server 
      - user.js
      - package-lock.json
      
